### ISSUE TITLE
Hooks can only be used within the Canvas component!

### ISSUE THREAD

**Issue by samueljoos** [tommasoturchi/react-three-mind#5]
Hi, 

My project breaks any time I add a r3f hook:
`Error: R3F: Hooks can only be used within the Canvas component!`

I think @react-three/fiber should be added as peerDependency in the package.json. I could be wrong though.

**Comment by tommasoturchi** [comment]
Hi Samuel,
I think there was the same issue a while ago and it got sorted out here: https://github.com/tommasoturchi/react-three-mind/issues/2
It's definitely a dependency issue, perhaps you have @react-three/fiber as a dependency of your project too but it's not required if you already have react-three-mind.
I'm working on rewriting the bundling and exporting from the PR mentioned here, which is probably going to fix all related issues: https://github.com/tommasoturchi/react-three-mind/issues/4
