### ISSUE TITLE
onAnchorFound /onAnchorLost causing performance issue

### ISSUE THREAD

**Issue by Charles19901210** [tommasoturchi/react-three-mind#6]
Hi,

First, thanks for sharing this package. It's really useful.

Now I applied react-three-mind to do some implement.  For some use cases, I have to use onAnchorFound/onAnchorLost to capture the anchor image is scanned or not. But after I added this two events, there is a serious performance issue on mobile. especially on android. 

Nearly below 10 fps on android. ios stays like 10~20 fps.
Also, the react component will be called more than one time when I use it.

Just wondering is there anyway can solve this issue? Or having some improvements. 

As I can think  now. If I want to do something related to anchor found/lost. this two events are must have.
Pretty keen to know how to solve this issue.  Thanks !

Charles

**Comment by paolocorti** [comment]
Hi,
i'm actually experiencing the same issue here. 
When the components where ARView rerender, something is not deallocating memory. 
Taking a heap snaphot after a rerender you can see the memory grows, and if you have multiple 
ARAnchor the effect is amplified (as you can see in the screenshot i took). Removing onAnchorFound and onAnchorLost the problems disappear.

<img width="192" alt="Screenshot 2023-01-12 at 10 22 44" src="https://user-images.githubusercontent.com/2910454/212094101-d8b95c7b-2473-4dad-a8a4-be3b8c7387fc.png">

@tommasoturchi i've pushed the code into my forked repo if you want to test it https://github.com/paolocorti/react-three-mind, i changed a bit the code of image-tracking example.
I'm gonna try to see if i can identify what's the problem in the meantime.

Thanks

**Comment by tommasoturchi** [comment]
Fixed with https://github.com/tommasoturchi/react-three-mind/issues/1
